### ISSUE TITLE
Error at start script

### ISSUE THREAD

**Issue by KonstantinFromRussia** [aidsoul/vk-to-telegram#2]
Start script at "Openserver"
error:
Fatal error: Uncaught Error: Class "Botpvt\Config\Config" not found in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Start.php:19 Stack trace: #0 W:\domains\bot1.ru\index.php(22): Botpvt\Start::vk() #1 {main} thrown in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Start.php on line 19

В общем все сделал по инструкции -запустил на open Server - PHP версии  8.1 - такая вот ошибка.

**Comment by aidsoul** [comment]
Здравствуйте, обновите данный [репозиторий](https://github.com/aidsoul/vk-to-telegram). Ошибка исправлена.

**Comment by KonstantinFromRussia** [comment]
Fatal error: Uncaught RedBeanPHP\RedException: Unsupported database (). in W:\domains\bot1.ru\vendor\gabordemooij\redbean\RedBeanPHP\Facade.php:472 Stack trace: #0 W:\domains\bot1.ru\vendor\gabordemooij\redbean\RedBeanPHP\Facade.php(413): RedBeanPHP\Facade::createToolbox() #1 W:\domains\bot1.ru\vendor\gabordemooij\redbean\RedBeanPHP\Facade.php(279): RedBeanPHP\Facade::addDatabase() #2 W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\DataBase\Connect.php(34): RedBeanPHP\Facade::setup() #3 W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Vk\Vk.php(58): Botpvt\DataBase\Connect->__construct() #4 W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Start.php(21): Botpvt\Vk\Vk->collectPush() #5 W:\domains\bot1.ru\index.php(23): Botpvt\Start::vk() #6 {main} thrown in W:\domains\bot1.ru\vendor\gabordemooij\redbean\RedBeanPHP\Facade.php on line 472

**Comment by aidsoul** [comment]
У вас не поддерживаемая база данных, проверьте правильность написания конфигурации базы данных. 
База данных должна быть MySQL!
  'Db'  => [
    'host'    => 'mysql:host=localhost',
    'dbName'  =>  'имя базы данных',
    'user'   =>  'имя пользователя'',
    'pass'    =>  'пароль пользователя'
  ]

**Comment by KonstantinFromRussia** [comment]
Я index.php делал из ссылки с  вашей статьи, вот здесь:
https://timeweb.com/ru/community/articles/kak-nastroit-avtoposting-zapisey-iz-gruppy-vk-v-telegram-kanal
Там у вас ошибка.
Написано:
  'host'          => '',
а должно быть видимо так:
'host' => 'mysql:host=localhost',
Сделал, теперь другая ошибка:
Warning: Undefined property: stdClass::$response in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Vk\Wall\ReceivedData.php on line 119

Warning: Attempt to read property "items" on null in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Vk\Wall\ReceivedData.php on line 119

Warning: foreach() argument must be of type array|object, null given in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Vk\Wall\ReceivedData.php on line 119

**Comment by KonstantinFromRussia** [comment]
Да, единственно - это может быть связано с тем,что группа закрытая???
Просто предполагал, что если я даю боту сервисный ключ приложения ВК -должны быть доступны и закрытые группы на которые я подписан.
Это не так???

**Comment by aidsoul** [comment]
Бот берёт данные из **одной** группы, и отправляет в телеграм-канал. 
Группа в ВК должна быть открытой. Для закрытых групп нужен "Implicit Flow".

Чтобы добавить несколько групп нужно создавать отдельные конфиги, для каждой группы.

> Данный бот - это автопостинг записей групп ВК в телеграм.

**Comment by KonstantinFromRussia** [comment]
В общем пробовал и так и сяк - генерировал токены разными методами, что нашел в инете.
Добился только того, что скрипт постит в Телеграм с Моей Стены.
Из других групп, хоть открытых, хоть закрытых - запускается, ошибок не выводит, но и не постит ничего.
Ограничений кстати нет каких-то у ВК или ТГ на обработку таких запросов????
Может рубит их???

**Comment by aidsoul** [comment]
Здесь можно узнать об ограничениях [VK api]( https://dev.vk.com/api/api-requests).

**Comment by KonstantinFromRussia** [comment]
Я понял, но в независимости от токена или ID группы - скрипт постит не из группы, а с моей СТЕНЫ

Смотрю ID приложения - именно того, что создавал под Бот.
Потом редактирую вот эту ссылку:
https://oauth.vk.com/authorize?client_id=ЗДЕСЬ ID ПРИЛОЖЕНИЯ&display=page&scope=notify,photos,friends,audio,video,notes,pages,docs,status,questions,offers,wall,groups,notifications,stats,offline&response_type=token&v=5.131&state=123456

Получаю в командной строке Токен - ставлю в скрипт, запускаю и получаю посты со своей стены, а не из указанной группы
Что я делаю не так????

Вот на всякий случай index.php

```
require_once __DIR__.'/vendor/autoload.php';
$config =  [
    'Vk'        =>[
   	    'token'         => 'здесь токен приложения',
   	    'idGroup'       => '7922819',
   	    'count'         => 20
    ],
    'Telegram'  =>[
      	'botApiKey'     => '',
      	'botName'       => '',
     	  'chatId'        =>  
    ],
    'Db'        =>[
       	'host'          => 'mysql:host=localhost',
       	'dbName'        =>  'bot1',
        'user'          =>  'root',
        'pass'          =>  'root'
      ],
  ];

Botpvt\Start::vk($config);
```

**Comment by aidsoul** [comment]
В  'idGroup' вы указываете свой идентификатор (личной странички) или идентификатор группы (id)?

**Comment by KonstantinFromRussia** [comment]
В том-то и дело что нет. Указываю именно ID группы

   	    'idGroup'       => '7922819',
![prio-info](https://user-images.githubusercontent.com/31459888/160897142-9337161a-bef0-4474-80b8-54eb6345aeb4.png)

 - а получаю со своей стены :(

**Comment by aidsoul** [comment]
Попробуйте вместо '7922819', написать 'prio_info'.

**Comment by KonstantinFromRussia** [comment]
Вроде работает - но как-то странно. После запуска сразу должны появляться в ТГ записи или с некоторой задержкой???
Как-то у вас похоже решен вопрос с тем, чтобы старые посты не тащил - правильно?
Но вот например я ставлю:
   	    'count'         => 20
и запускаю появляются 5-7 постов - хотя на стене их много больше
потом меняю на:
   	    'count'         => 50
снова запускаю и и появляется еще 3-5 постов более старых.
Вот как-то так, сразу 20 записей со стены или 50 как указано в 'count' чего-то не показываются.

**Comment by KonstantinFromRussia** [comment]
Да и потом, опять-же в вашей статье:
https://timeweb.com/ru/community/articles/kak-nastroit-avtoposting-zapisey-iz-gruppy-vk-v-telegram-kanal
написано про Копируем сервисный ключ доступа - зачем он нужен совсем непонятно.
Я сначала предполагал что  его надо вписывать вот сюда:
'token'         => 
но выяснилось. в процессе что туда надо вписывать именно токен, который берется совсем в другом месте, а не  сервисный ключ доступа.
Или я что-то не понимаю и сервисный ключ доступа все-таки используется????

**Comment by aidsoul** [comment]
Увы, задержек не избежать. Всё-таки в процессе участвуют несколько серверов, которые отдают и принимают большие данные.
Это автопостинг, он лучше всего подходит для удалённого сервера. Поставил, и он будет сам тянуть посты с группы в ВК и отправлять в Телеграм. Он отправляет те данные, которых нет в канале Телеграма.

В этой версии, бот не умеет отправлять некоторые посты из группы ВК. Не отправляет посты с видео.
Вероятно, завтра добавлю обновлённую версию бота. Эта версия будет быстрее.

**Comment by aidsoul** [comment]
> Да и потом, опять-же в вашей статье: https://timeweb.com/ru/community/articles/kak-nastroit-avtoposting-zapisey-iz-gruppy-vk-v-telegram-kanal написано про Копируем сервисный ключ доступа - зачем он нужен совсем непонятно. Я сначала предполагал что его надо вписывать вот сюда: 'token' => но выяснилось. в процессе что туда надо вписывать именно токен, который берется совсем в другом месте, а не сервисный ключ доступа. Или я что-то не понимаю и сервисный ключ доступа все-таки используется????

Нужно использовать "**Сервисный ключ доступа**", он же **token**. Модераторы немного исказили статью.

**Comment by aidsoul** [comment]
@KonstantinFromRussia, лучше использовать удалённый сервер или локальный на "**Debian**". 
Скорость заметно выше, чем использовать: "Open Server Panel" или "XAMPP".

**Comment by KonstantinFromRussia** [comment]
Докладываю!
Сделал 5 копий скрипта - каждый под отдельную группу ВК.
Запускаю по крону последовательно. Сообщения подтягиваются - правда не все, некоторые по непонятным причинам пропускаются.
И еще время от времени, в какой-то из 5-ти копий выскакивает вот такая ошибка:


 Warning: Undefined array key "id" in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Vk\Vk.php on line 66

Warning: Undefined array key "text" in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Vk\Vk.php on line 67

Fatal error: Uncaught TypeError: Botpvt\DataBase\Query::checkPost(): Argument #1 ($postId) must be of type int, null given, called in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Vk\Vk.php on line 77 and defined in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\DataBase\Query.php:75 Stack trace: #0 W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Vk\Vk.php(77): Botpvt\DataBase\Query->checkPost() #1 W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\Start.php(21): Botpvt\Vk\Vk->collectPush() #2 W:\domains\bot1.ru\bot2.php(22): Botpvt\Start::vk() #3 {main} thrown in W:\domains\bot1.ru\vendor\aidsoul\botpvt\src\DataBase\Query.php on line 75

**Comment by KonstantinFromRussia** [comment]
Ну то есть 5-ть копий именно файла index.php, которые находятся в одной папке 
index1.php - одна группа
index2.php - вторая группа
и так далее..
папка с самим скриптом - не меняется.
Да а базы под каждую группу - естественно разные
base1
base2
и так далее...

**Comment by aidsoul** [comment]
Нет необходимости создавать под каждый конфиг, новую базу данных. 
Рекомендую перейти на новую версию: https://github.com/aidsoul/vktote

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @KonstantinFromRussia)
